server {
    listen 80;

    # React 정적 파일 서빙
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;   # React Router 새로고침 대응
    }

    # /api 요청 → 백엔드 서비스로 전달
    location /api {
        proxy_pass http://bookapp-backend-svc:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # /videos 요청 → 백엔드 서비스로 전달
    location /videos {
        proxy_pass http://bookapp-backend-svc:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # /books 요청 → 백엔드 서비스로 전달
    location /books {
        proxy_pass http://bookapp-backend-svc:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}