version: 0.2

phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com
      - aws eks update-kubeconfig --region ap-northeast-2 --name user190-cluster

  build:
    commands:
      # Backend 빌드 & push
      - docker build -t user190-repo2 ./backend
      - docker tag user190-repo2:latest 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user190-repo2:latest
      - docker push 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user190-repo2:latest

      # Frontend 빌드 & push
      - docker build -t user190-repo3 ./frontend
      - docker tag user190-repo3:latest 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user190-repo3:latest
      - docker push 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user190-repo3:latest

  post_build:
  commands:
    - kubectl apply -f k8s/ -n user190-app --validate=false
    - kubectl rollout restart deployment -n user190-app