version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd frontend
      - npm install
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - cd frontend
      - npm run build
    finally:
      - echo This is the finally block execution!
artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'